language: objective-c
before_install:
  - brew update
  - brew reinstall xctool
  - xcrun simctl list
script: xctool project IGInterfaceDataTable.xcodeproj scheme 'IGInterfaceDataTable' -configuration Debug -sdk iphonesimulator8.3 -arch i386 build
osx_image: beta-xcode6.3

# whitelist
branches:
  only:
    - master
